spring:
  application:
    name: super-oauth2
  datasource:
    url: jdbc:mysql://localhost:3306/superrecarga?serverTimezone=UTC
    username: super
    password: superrecarga
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      pool-name: superPoolOaut
      max-lifetime: 18000000
      connection-timeout: 30000
      auto-commit: false
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: false
    open-in-view: false

security:
  oauth2:
    client:
#      scope: read,write
      client-id: fb1d363d-ed3d-4ee4-a5a3-3b9a44e112f6
      client-secret: 1769a946-90c2-430f-843d-cc9649721225
    authorization:
      jwt:
        key-value:

logging:
  level:
    org:
      springframework:
        security: DEBUG
